language: node_js
node_js:
  - stable
cache:
  directories:
    - client/node_modules
    - server/node_modules
script:
  - npm run --prefix client build
  - npm run --prefix client lint
  - npm run --prefix client test
  - npm run --prefix server build
  - npm run --prefix server lint
  - npm run --prefix server test
